### ISSUE TITLE
uint fields should be json-marshalled to strings and not uints

### ISSUE THREAD

**Issue by samlaf** [umbracle/go-eth-consensus#29]
Is it possible that this library does not espect the [beacon api types](https://github.com/ethereum/beacon-APIs)?

For eg., when I query my node for the chain's [genesis data](https://ethereum.github.io/beacon-APIs/#/Beacon/getGenesis), I get this encoding:
```
{
  "data": {
    "genesis_time": "1590832934",
    "genesis_validators_root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
    "genesis_fork_version": "0x00000000"
  }
}
```
Note that genesis_time is encoded as a string! This seems to follow the [official beacon api's string type](https://github.com/ethereum/beacon-APIs/blob/6669d981486b7034fc9911fdf7be157343b6ea5e/types/primitive.yaml#L20)

However, if we look at the [BeaconStatePhase0](https://github.com/umbracle/go-eth-consensus/blob/22db096317980030dc4c844470cb2da563255563/structs.go#L123), say, in this library, the state is not encoded as a string. This results in the beacon chain expecting a json object like
```
{
   ...
   "genesis_time": 1590832934
   ...
}
```

Hence when I try to parse the beaconstate returned from my node with this library, I get this error
```
panic: json: cannot unmarshal string into Go struct field BeaconStatePhase0.genesis_time of type uint64
```

Am I doing something wrong? Or is this library just not up to date with the latest typing changes?

**Comment by ferranbt** [comment]
Hi!

Note that the output of the genesis data endpoint [here](https://github.com/umbracle/go-eth-consensus/blob/main/http/beacon.go#L18) also uses `uint64` like `BeaconStatePhase0`. Are you using the `http` library? I cannot find any endpoint that returns the beacon state.

If you have a `json` file that follows the `beaconAPI` format you can use [this](https://github.com/umbracle/go-eth-consensus/blob/main/http/encoding.go#L116) method to decode the `BeaconState` object. The struct types do not do any casting but all that is handled by that function.

**Comment by samlaf** [comment]
Hey :) 

Thanks for answering.
I might have totally been misunderstanding this library. Regarding "I cannot find any endpoint that returns the beacon state", I was using the beacon api's [debug endpoint](https://ethereum.github.io/beacon-APIs/#/Debug) /eth/v2/debug/beacon/states

Anyways using eth-go2-client library now instead. I will get back to this answer if I ever switch back to this repo. Closing for now :)
